id: dbt_build
namespace: company.data_engineering

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: check_files
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - ls -la /app/dbt-project/
          - cp -R /app/dbt-project/* .
          - cp -R /keys/* .
          - ls
      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: ghcr.io/kestra-io/dbt-bigquery:latest
        projectDir: crypto
        commands:
          - dbt deps
          - dbt build

triggers:
  - id: once_per_hour
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"